spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/scheduler_quartz?createDatabaseIfNotExist=true
    username: root
    password: 111111
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: Asia/Seoul
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
      data-locations: classpath:data.sql
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: SchedulerClustered
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 20000
            useProperties: false
            misfireThreshold: 60000
          threadPool:
            threadCount: 10

scheduler:
  lock:
    schedule-seconds: 30
    execution-seconds: 300
  quartz:
    job-class: com.example.scheduler.adapters.in.scheduler.TaskExecutionJob
