spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/scheduler_spring?createDatabaseIfNotExist=true
    username: root
    password: 111111
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: Asia/Seoul
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
      data-locations: classpath:data.sql

scheduler:
  lock:
    schedule-seconds: 30
    execution-seconds: 300
  batch-size: 20
  poll-interval-ms: 1000
